# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
Temporary ordering helpers extracted from origin/main client-sdks/stainless/openapi.yml.

These lists help the new generator match the previous ordering so that diffs
remain readable while we debug schema content regressions. Remove once stable.
"""

LEGACY_PATH_ORDER = [
    "/v1/batches",
    "/v1/batches/{batch_id}",
    "/v1/batches/{batch_id}/cancel",
    "/v1/chat/completions",
    "/v1/chat/completions/{completion_id}",
    "/v1/completions",
    "/v1/conversations",
    "/v1/conversations/{conversation_id}",
    "/v1/conversations/{conversation_id}/items",
    "/v1/conversations/{conversation_id}/items/{item_id}",
    "/v1/embeddings",
    "/v1/files",
    "/v1/files/{file_id}",
    "/v1/files/{file_id}/content",
    "/v1/health",
    "/v1/inspect/routes",
    "/v1/models",
    "/v1/models/{model_id}",
    "/v1/prompts",
    "/v1/prompts/{prompt_id}",
    "/v1/prompts/{prompt_id}/set-default-version",
    "/v1/prompts/{prompt_id}/versions",
    "/v1/providers",
    "/v1/providers/{provider_id}",
    "/v1/responses",
    "/v1/responses/{response_id}",
    "/v1/responses/{response_id}/input_items",
    "/v1/tool-runtime/invoke",
    "/v1/tool-runtime/list-tools",
    "/v1/toolgroups",
    "/v1/toolgroups/{toolgroup_id}",
    "/v1/admin/tools",
    "/v1/tools/{tool_name}",
    "/v1/vector-io/insert",
    "/v1/vector-io/query",
    "/v1/vector_stores",
    "/v1/vector_stores/{vector_store_id}",
    "/v1/vector_stores/{vector_store_id}/file_batches",
    "/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}",
    "/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel",
    "/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files",
    "/v1/vector_stores/{vector_store_id}/files",
    "/v1/vector_stores/{vector_store_id}/files/{file_id}",
    "/v1/vector_stores/{vector_store_id}/files/{file_id}/content",
    "/v1/vector_stores/{vector_store_id}/search",
    "/v1/version",
    "/v1alpha/inference/rerank",
]

LEGACY_SCHEMA_ORDER = [
    "Error",
    "ListBatchesResponse",
    "CreateBatchRequest",
    "Batch",
    "Order",
    "ListOpenAIChatCompletionResponse",
    "OpenAIAssistantMessageParam",
    "OpenAIChatCompletionContentPartImageParam",
    "OpenAIChatCompletionContentPartParam",
    "OpenAIChatCompletionContentPartTextParam",
    "OpenAIChatCompletionToolCall",
    "OpenAIChatCompletionToolCallFunction",
    "OpenAIChatCompletionUsage",
    "OpenAIChoice",
    "OpenAIChoiceLogprobs",
    "OpenAIDeveloperMessageParam",
    "OpenAIFile",
    "OpenAIFileFile",
    "OpenAIImageURL",
    "OpenAIMessageParam",
    "OpenAISystemMessageParam",
    "OpenAITokenLogProb",
    "OpenAIToolMessageParam",
    "OpenAITopLogProb",
    "OpenAIUserMessageParam",
    "OpenAIJSONSchema",
    "OpenAIResponseFormatJSONObject",
    "OpenAIResponseFormatJSONSchema",
    "OpenAIResponseFormatParam",
    "OpenAIResponseFormatText",
    "OpenAIChatCompletionRequestWithExtraBody",
    "OpenAIChatCompletion",
    "OpenAIChatCompletionChunk",
    "OpenAIChoiceDelta",
    "OpenAIChunkChoice",
    "OpenAICompletionWithInputMessages",
    "OpenAICompletionRequestWithExtraBody",
    "OpenAICompletion",
    "OpenAICompletionChoice",
    "ConversationItem",
    "OpenAIResponseAnnotationCitation",
    "OpenAIResponseAnnotationContainerFileCitation",
    "OpenAIResponseAnnotationFileCitation",
    "OpenAIResponseAnnotationFilePath",
    "OpenAIResponseAnnotations",
    "OpenAIResponseContentPartRefusal",
    "OpenAIResponseInputFunctionToolCallOutput",
    "OpenAIResponseInputMessageContent",
    "OpenAIResponseInputMessageContentFile",
    "OpenAIResponseInputMessageContentImage",
    "OpenAIResponseInputMessageContentText",
    "OpenAIResponseMCPApprovalRequest",
    "OpenAIResponseMCPApprovalResponse",
    "OpenAIResponseMessage",
    "OpenAIResponseOutputMessageContent",
    "OpenAIResponseOutputMessageContentOutputText",
    "OpenAIResponseOutputMessageFileSearchToolCall",
    "OpenAIResponseOutputMessageFunctionToolCall",
    "OpenAIResponseOutputMessageMCPCall",
    "OpenAIResponseOutputMessageMCPListTools",
    "OpenAIResponseOutputMessageWebSearchToolCall",
    "CreateConversationRequest",
    "Conversation",
    "UpdateConversationRequest",
    "ConversationDeletedResource",
    "ConversationItemList",
    "AddItemsRequest",
    "ConversationItemDeletedResource",
    "OpenAIEmbeddingsRequestWithExtraBody",
    "OpenAIEmbeddingData",
    "OpenAIEmbeddingUsage",
    "OpenAIEmbeddingsResponse",
    "OpenAIFilePurpose",
    "ListOpenAIFileResponse",
    "OpenAIFileObject",
    "ExpiresAfter",
    "OpenAIFileDeleteResponse",
    "Response",
    "HealthInfo",
    "RouteInfo",
    "ListRoutesResponse",
    "OpenAIModel",
    "OpenAIListModelsResponse",
    "Model",
    "ModelType",
    "Prompt",
    "ListPromptsResponse",
    "CreatePromptRequest",
    "UpdatePromptRequest",
    "SetDefaultVersionRequest",
    "ProviderInfo",
    "ListProvidersResponse",
    "ListOpenAIResponseObject",
    "OpenAIResponseError",
    "OpenAIResponseInput",
    "OpenAIResponseInputToolFileSearch",
    "OpenAIResponseInputToolFunction",
    "OpenAIResponseInputToolWebSearch",
    "OpenAIResponseObjectWithInput",
    "OpenAIResponseOutput",
    "OpenAIResponsePrompt",
    "OpenAIResponseText",
    "OpenAIResponseTool",
    "OpenAIResponseToolMCP",
    "OpenAIResponseUsage",
    "ResponseGuardrailSpec",
    "OpenAIResponseInputTool",
    "OpenAIResponseInputToolMCP",
    "CreateOpenaiResponseRequest",
    "OpenAIResponseObject",
    "OpenAIResponseContentPartOutputText",
    "OpenAIResponseContentPartReasoningSummary",
    "OpenAIResponseContentPartReasoningText",
    "OpenAIResponseObjectStream",
    "OpenAIResponseObjectStreamResponseCompleted",
    "OpenAIResponseObjectStreamResponseContentPartAdded",
    "OpenAIResponseObjectStreamResponseContentPartDone",
    "OpenAIResponseObjectStreamResponseCreated",
    "OpenAIResponseObjectStreamResponseFailed",
    "OpenAIResponseObjectStreamResponseFileSearchCallCompleted",
    "OpenAIResponseObjectStreamResponseFileSearchCallInProgress",
    "OpenAIResponseObjectStreamResponseFileSearchCallSearching",
    "OpenAIResponseObjectStreamResponseFunctionCallArgumentsDelta",
    "OpenAIResponseObjectStreamResponseFunctionCallArgumentsDone",
    "OpenAIResponseObjectStreamResponseInProgress",
    "OpenAIResponseObjectStreamResponseIncomplete",
    "OpenAIResponseObjectStreamResponseMcpCallArgumentsDelta",
    "OpenAIResponseObjectStreamResponseMcpCallArgumentsDone",
    "OpenAIResponseObjectStreamResponseMcpCallCompleted",
    "OpenAIResponseObjectStreamResponseMcpCallFailed",
    "OpenAIResponseObjectStreamResponseMcpCallInProgress",
    "OpenAIResponseObjectStreamResponseMcpListToolsCompleted",
    "OpenAIResponseObjectStreamResponseMcpListToolsFailed",
    "OpenAIResponseObjectStreamResponseMcpListToolsInProgress",
    "OpenAIResponseObjectStreamResponseOutputItemAdded",
    "OpenAIResponseObjectStreamResponseOutputItemDone",
    "OpenAIResponseObjectStreamResponseOutputTextAnnotationAdded",
    "OpenAIResponseObjectStreamResponseOutputTextDelta",
    "OpenAIResponseObjectStreamResponseOutputTextDone",
    "OpenAIResponseObjectStreamResponseReasoningSummaryPartAdded",
    "OpenAIResponseObjectStreamResponseReasoningSummaryPartDone",
    "OpenAIResponseObjectStreamResponseReasoningSummaryTextDelta",
    "OpenAIResponseObjectStreamResponseReasoningSummaryTextDone",
    "OpenAIResponseObjectStreamResponseReasoningTextDelta",
    "OpenAIResponseObjectStreamResponseReasoningTextDone",
    "OpenAIResponseObjectStreamResponseRefusalDelta",
    "OpenAIResponseObjectStreamResponseRefusalDone",
    "OpenAIResponseObjectStreamResponseWebSearchCallCompleted",
    "OpenAIResponseObjectStreamResponseWebSearchCallInProgress",
    "OpenAIResponseObjectStreamResponseWebSearchCallSearching",
    "OpenAIDeleteResponseObject",
    "ListOpenAIResponseInputItem",
    "AggregationFunctionType",
    "ArrayType",
    "BooleanType",
    "ChatCompletionInputType",
    "CompletionInputType",
    "JsonType",
    "NumberType",
    "ObjectType",
    "StringType",
    "UnionType",
    "InvokeToolRequest",
    "ImageContentItem",
    "InterleavedContent",
    "InterleavedContentItem",
    "TextContentItem",
    "ToolInvocationResult",
    "URL",
    "ToolDef",
    "ListToolDefsResponse",
    "ToolGroup",
    "ListToolGroupsResponse",
    "Chunk",
    "ChunkMetadata",
    "InsertChunksRequest",
    "QueryChunksRequest",
    "QueryChunksResponse",
    "VectorStoreFileCounts",
    "VectorStoreListResponse",
    "VectorStoreObject",
    "VectorStoreChunkingStrategy",
    "VectorStoreChunkingStrategyAuto",
    "VectorStoreChunkingStrategyStatic",
    "VectorStoreChunkingStrategyStaticConfig",
    "OpenAICreateVectorStoreRequestWithExtraBody",
    "OpenaiUpdateVectorStoreRequest",
    "VectorStoreDeleteResponse",
    "OpenAICreateVectorStoreFileBatchRequestWithExtraBody",
    "VectorStoreFileBatchObject",
    "VectorStoreFileStatus",
    "VectorStoreFileLastError",
    "VectorStoreFileObject",
    "VectorStoreFilesListInBatchResponse",
    "VectorStoreListFilesResponse",
    "OpenaiAttachFileToVectorStoreRequest",
    "OpenaiUpdateVectorStoreFileRequest",
    "VectorStoreFileDeleteResponse",
    "bool",
    "VectorStoreContent",
    "VectorStoreFileContentResponse",
    "OpenaiSearchVectorStoreRequest",
    "VectorStoreSearchResponse",
    "VectorStoreSearchResponsePage",
    "VersionInfo",
    "RerankRequest",
    "RerankData",
    "RerankResponse",
    "RegisterModelRequest",
    "ParamType",
    "RegisterToolGroupRequest",
]

LEGACY_RESPONSE_ORDER = ["BadRequest400", "TooManyRequests429", "InternalServerError500", "DefaultError"]

LEGACY_TAGS = [
    {
        "description": "Administrative APIs for inspecting providers, routes, health, and version.",
        "name": "Admin",
        "x-displayName": "Admin",
    },
    {
        "description": "APIs for creating and interacting with agentic systems.",
        "name": "Agents",
        "x-displayName": "Agents",
    },
    {
        "description": "The API is designed to allow use of openai client libraries for seamless integration.\n"
        "\n"
        "This API provides the following extensions:\n"
        " - idempotent batch creation\n"
        "\n"
        "Note: This API is currently under active development and may undergo changes.",
        "name": "Batches",
        "x-displayName": "Batches",
    },
    {
        "description": "External tool and service connectors.",
        "name": "Connectors",
        "x-displayName": "Connectors",
    },
    {
        "description": "Protocol for conversation management operations.",
        "name": "Conversations",
        "x-displayName": "Conversations",
    },
    {
        "description": "Document ingestion and chunking.",
        "name": "File Processors",
        "x-displayName": "File Processors",
    },
    {
        "description": "This API is used to upload documents that can be used with other OGX APIs.",
        "name": "Files",
        "x-displayName": "Files",
    },
    {
        "description": "OGX Inference API for generating completions, chat completions, and embeddings.\n"
        "\n"
        "This API provides the raw interface to the underlying models. Three kinds of models are supported:\n"
        '- LLM models: these models generate "raw" and "chat" (conversational) completions.\n'
        "- Embedding models: these models generate embeddings to be used for semantic search.\n"
        "- Rerank models: these models reorder the documents based on their relevance to a query.",
        "name": "Inference",
        "x-displayName": "Inference",
    },
    {
        "description": "APIs for inspecting the OGX service, including health status, available API routes with "
        "methods and implementing providers.",
        "name": "Inspect",
        "x-displayName": "Inspect",
    },
    {
        "description": "Google Interactions API compatibility layer.",
        "name": "Interactions",
        "x-displayName": "Interactions",
    },
    {
        "description": "Anthropic Messages API compatibility layer for creating messages and counting tokens.",
        "name": "Messages",
        "x-displayName": "Messages",
    },
    {"description": "", "name": "Models"},
    {"description": "Protocol for prompt management operations.", "name": "Prompts", "x-displayName": "Prompts"},
    {
        "description": "Providers API for inspecting, listing, and modifying providers and their configurations.",
        "name": "Providers",
        "x-displayName": "Providers",
    },
    {"description": "", "name": "ToolGroups"},
    {"description": "", "name": "ToolRuntime"},
    {
        "description": "Tool listing and management.",
        "name": "Tools",
        "x-displayName": "Tools",
    },
    {"description": "", "name": "VectorIO"},
    {
        "description": "OpenAI Responses API for agent orchestration with tool use, multi-turn conversations, and background processing.",
        "name": "Responses",
        "x-displayName": "Responses",
    },
]

LEGACY_TAG_ORDER = [
    "Admin",
    "Agents",
    "Batches",
    "Connectors",
    "Conversations",
    "File Processors",
    "Files",
    "Inference",
    "Inspect",
    "Interactions",
    "Messages",
    "Models",
    "Prompts",
    "Providers",
    "Responses",
    "ToolGroups",
    "ToolRuntime",
    "Tools",
    "VectorIO",
]

LEGACY_TAG_GROUPS = [
    {
        "name": "Operations",
        "tags": [
            "Admin",
            "Agents",
            "Batches",
            "Connectors",
            "Conversations",
            "File Processors",
            "Files",
            "Inference",
            "Inspect",
            "Interactions",
            "Messages",
            "Models",
            "Prompts",
            "Providers",
            "Responses",
            "ToolGroups",
            "ToolRuntime",
            "Tools",
            "VectorIO",
        ],
    }
]

LEGACY_SECURITY = [{"Default": []}]

LEGACY_OPERATION_KEYS = [
    "responses",
    "tags",
    "summary",
    "description",
    "operationId",
    "parameters",
    "requestBody",
    "deprecated",
]
